spring:
  rabbitmq:
    host: management.deschen.cn
    port: 5672
    username: deschen
    password: root123
eureka:
  instance:
    prefer-ip-address: true # 当调用getHostname获取实例的hostname时，返回ip而不是host名称
    instance-id: ${spring.application.name}:${server.port} # DESKTOP-2MVEC12:user-service:8081：是示例的名称，instance-id是区分同一服务的不同实例的唯一标准，因此不能重复
  compression:
    request:
      enabled: true   # 开启请求压缩，默认false
      mime-types:  text/html,application/xml,application/json # 默认设置压缩的数据类型
      min-request-size: 2048 # 默认设置触发压缩的大小下限
    response:
      enabled: true   # 开启响应压缩，默认false
zuul:
  host:
    connect-timeout-millis: 120000 #HTTP连接超时大于Hystrix的超时时间
    socket-timeout-millis: 120000   #socket超时
  prefix: /api   # 路由前缀
  ignored-services: "*"  # 忽略的应用，不暴露接口
  routes:
    ep-category:
      path: /ep/category/**
      serviceId: ep-category
      strip-prefix: false
      sensitiveHeaders:
    ep-product:
      path: /ep/product/**
      serviceId: ep-product
      strip-prefix: false
      sensitiveHeaders:
    ep-uploadFile:
      path: /ep/file/**
      serviceId: ep-uploadFile
      strip-prefix: false
      sensitiveHeaders:
    ep-course:
      path: /ep/course/**
      serviceId: ep-course
      strip-prefix: false
      sensitiveHeaders:
    ep-order:
      path: /ep/order/**
      serviceId: ep-order
      strip-prefix: false
      sensitiveHeaders:
    ep-pay:
      path: /ep/pay/**
      serviceId: ep-pay
      strip-prefix: false
      sensitiveHeaders:
    ep-auth:
      path: /ep/auth/**
      serviceId: ep-auth
      strip-prefix: false
      sensitiveHeaders:
# `@FeignClient`注解修改的客户端在被代理时，都会创建一个新的Fegin.Logger实例。我们需要额外指定这个日志的级别才可以。
logging:
  level:
    com.ep: debug
# 参数计算重试的次数：MaxAutoRetries+MaxAutoRetriesNextServer+(MaxAutoRetries *MaxAutoRetriesNextServer) 即重试3次 则一共产生4次调用
ribbon:
  ConnectTimeout: 60000 # 连接超时时间(ms)
  ReadTimeout: 60000 # 通信超时时间(ms)
  MaxAutoRetriesNextServer: 1 # 同一服务不同实例的重试次数，不包括首次调用
  MaxAutoRetries: 1 # 同一实例的重试次数，不包括首次调用
